import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { operationSchema } from "../../features/experiments/contracts";
import { planOperation } from "../../features/experiments/operators";

test("prepare, retry, inspect, annotate and compare a Weave variant", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let calls = 0;
  const requests: ReturnType<typeof operationSchema.parse>[] = [];
  await page.route("**/api/**", async route => {
    if (!route.request().url().endsWith('/api/weave')) return route.fulfill({ status: 503, json: { error: "Offline UI verification" } });
    calls++;
    const raw = route.request().postDataJSON();
    if (calls === 1) return route.fulfill({ status: 503, json: { error: "Temporary generation failure." } });
    const op = operationSchema.parse({ ...raw, id: randomUUID(), version: 1, kind: "weave", goal: "Combine these ideas", constraints: [] });
    requests.push(op);
    const card = { title: calls === 2 ? 'A repair supper' : 'A teaching supper', summary: 'A shared table for repairing and learning.', body: calls === 2 ? 'Shared meals make repair waiting useful. Tools are borrowed at the table.' : 'Shared teaching makes repair waiting useful. Tools are borrowed at the table.' };
    await route.fulfill({ json: { card, contributions: ['The shared meal', 'The borrowed tools'], receipt: { operation: op, manifest: planOperation(op), status: 'committed', at: new Date().toISOString() }, weaveMappings: op.weave?.selections.map(s => ({ selectionId: s.id, status: 'transformed', explanation: 'The contribution changes the shared activity.', output: { field: 'body', text: 'Tools are borrowed at the table.' } })) } });
  });
  await page.goto('/');
  await page.getByRole('button', { name: /^Thoughts / }).click();
  for (const title of ['A food hall', 'A shared tool library']) await page.locator('.catalogue-entry').filter({ has: page.getByText(title, { exact: true }) }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Close panel', exact: true }).click();
  const camera = () => page.locator('.react-flow__viewport').getAttribute('style');
  const before = await camera();
  await page.locator('.selection-bar').getByRole('button', { name: 'Weave', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'Prepare Weave', exact: true });
  await expect(panel).toBeVisible();
  const field = page.getByLabel('Carry forward · A food hall', { exact: true });
  await field.fill('Shared meals');
  await page.getByLabel('Carry forward · A shared tool library', { exact: true }).fill('Borrowing and repair');
  await panel.getByText('Choose an excerpt (optional)', { exact: true }).first().click();
  const sourceText = page.getByLabel('Source text · A food hall', { exact: true });
  await sourceText.focus(); await sourceText.press('ControlOrMeta+a');
  await panel.getByRole('button', { name: 'Use selected excerpt', exact: true }).click();
  await expect(panel.locator('blockquote')).not.toBeEmpty();
  await page.getByLabel('How should they interact? (optional)', { exact: true }).fill('Let waiting become a shared meal');
  await expect.poll(camera).toBe(before);
  await expect(panel).toBeVisible();
  expect(await panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('weave-preparation.png') });
  await panel.getByRole('button', { name: 'Weave contributions', exact: true }).click();
  await expect(panel.getByRole('alert')).toContainText('Temporary generation failure');
  await expect(field).toHaveValue('Shared meals');
  await panel.getByRole('button', { name: 'Try Weave again', exact: true }).click();
  const result = page.getByRole('dialog', { name: 'A repair supper', exact: true });
  await expect(result).toBeVisible();
  expect(requests[0].weave!.selections[0].text).toBe('Shared meals');
  expect(requests[0].weave!.selections[0].excerpt!.text.length).toBeGreaterThan(0);
  await expect.poll(camera).toBe(before);
  await result.getByText('Selected contributions · revision 1', { exact: true }).click();
  await result.getByText('Source revision 1 · A food hall', { exact: true }).click();
  await result.getByText('Result passage · body', { exact: true }).first().click();
  await expect(result.locator('mark:visible')).toHaveText('Tools are borrowed at the table.');
  await result.getByText('Add your interpretation', { exact: true }).first().click();
  await result.getByLabel('Your interpretation · A food hall', { exact: true }).fill('The meal still feels incidental.');
  await result.getByRole('button', { name: 'Save interpretation', exact: true }).first().click();
  await expect(result.getByText('Your note', { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('weave-inspection.png') });
  await result.getByRole('button', { name: 'Change a contribution', exact: true }).click();
  await field.fill('Shared teaching');
  await panel.getByRole('button', { name: 'Weave contributions', exact: true }).click();
  const variant = page.getByRole('dialog', { name: 'A teaching supper', exact: true });
  await expect(variant).toBeVisible();
  await variant.getByText('Selected contributions · revision 1', { exact: true }).click();
  await variant.getByRole('button', { name: 'Compare with original', exact: true }).click();
  const comparison = page.getByRole('dialog', { name: 'Compare Weave variants', exact: true });
  await expect(comparison.getByRole('heading', { name: 'A repair supper', exact: true })).toBeVisible();
  await expect(comparison.getByRole('heading', { name: 'A teaching supper', exact: true })).toBeVisible();
  await expect(comparison.locator('ins').filter({ hasText: /^teaching$/ })).toHaveText('teaching');
  expect(await comparison.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('weave-comparison.png') });
  await comparison.getByRole('button', { name: 'Return to result', exact: true }).click();
  await expect.poll(camera).toBe(before);
  await page.waitForTimeout(700); // Existing debounced IndexedDB save.
  await page.reload();
  await page.getByRole('button', { name: /^Thoughts / }).click();
  await expect(page.locator('.catalogue-entry').filter({ has: page.getByText('A repair supper', { exact: true }) })).toBeVisible();
  await expect(page.locator('.catalogue-entry').filter({ has: page.getByText('A teaching supper', { exact: true }) })).toBeVisible();
  expect(calls).toBe(3); expect(errors).toEqual([]);
});

test('whole-card Weave remains available and background completion preserves the current pane', async ({ page }) => {
  let finish: (() => void) | undefined;
  let calls = 0;
  await page.route('**/api/**', async route => {
    if (!route.request().url().endsWith('/api/weave')) return route.fulfill({ status: 503, json: { error: 'Offline UI verification' } });
    calls++;
    const input = route.request().postDataJSON();
    expect(input.weave).toBeUndefined();
    const op = operationSchema.parse({ ...input, id: randomUUID(), version: 1, kind: 'weave', goal: 'Combine these ideas', constraints: [] });
    await new Promise<void>(resolve => { finish = resolve; });
    await route.fulfill({ json: { card: { title: 'Whole-card result', summary: 'A result', body: 'A complete idea.' }, contributions: ['One', 'Two'], receipt: { operation: op, manifest: planOperation(op), status: 'committed', at: new Date().toISOString() } } });
  });
  await page.goto('/');
  await page.getByRole('button', { name: /^Thoughts / }).click();
  for (const title of ['A food hall', 'A shared tool library']) await page.locator('.catalogue-entry').filter({ has: page.getByText(title, { exact: true }) }).getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Close panel', exact: true }).click();
  await page.locator('.selection-bar').getByRole('button', { name: 'Weave', exact: true }).click();
  await page.getByRole('button', { name: 'Weave whole cards', exact: true }).click();
  await expect.poll(() => !!finish).toBe(true);
  await expect(page.getByRole('button', { name: 'Weaving…', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Close panel', exact: true }).click();
  await page.getByRole('button', { name: /^Thoughts / }).click();
  finish!();
  await expect(page.locator('.weave-notice')).toContainText('Whole-card result');
  await expect(page.locator('.catalogue-panel')).toBeVisible();
  await page.getByRole('button', { name: 'Close panel', exact: true }).click();
  await page.getByRole('button', { name: 'Open result', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Whole-card result', exact: true })).toBeVisible();
  expect(calls).toBe(1);
});
