import { z } from "zod";
import { receiptSchema, snapshotSchema, type Snapshot } from "../experiments/contracts";
import { weaveInputSchema, weaveMappingsSchema, validateWeaveInput, validateWeaveMappings, type WeaveInput } from "../experiments/weave";
import type { Thought, CardRevision } from "./domain";
import { stableJson } from "./stable-json";
import { firstRevision } from "./card-revisions";

export type WeaveDraft = { sources: Snapshot[]; weave: WeaveInput };
export function snapshotOf(card: Thought, revision = card.revision): Snapshot {
  const source = card.revisions.find(r => r.number === revision);
  if (!source) throw new Error("Source revision unavailable.");
  return { id: card.id, revision, title: source.title, summary: source.summary, body: source.body, ...(source.contribution !== undefined ? { contribution: source.contribution } : {}) };
}
export function newWeaveDraft(cards: Thought[]): WeaveDraft {
  return { sources: cards.map(c => snapshotOf(c)), weave: { version: 1, interaction: "", selections: cards.map(c => ({ id: crypto.randomUUID(), sourceId: c.id, sourceRevision: c.revision, text: c.contribution.slice(0, 2000) })) } };
}
export function weaveRevision(card: Thought) {
  return card.revisions.findLast(r => r.weaveMappings && (r.receipt?.operation ?? r.experiment?.operation)?.weave);
}
export function variantDraft(card: Thought, revision: CardRevision): WeaveDraft {
  const operation = revision.receipt?.operation ?? revision.experiment?.operation;
  if (!operation?.weave) throw new Error("The selected contributions are unavailable.");
  return structuredClone({ sources: operation.sources, weave: { ...operation.weave, variantOf: snapshotOf(card, revision.number) } });
}
// Receipts retain original IDs and exact snapshots on import. Never point an old
// receipt at a conflicting local card just because its original ID is the same.
export function resolveSnapshot(source: Snapshot, cards: Thought[]) {
  return cards.find(c => (c.id === source.id || c.importedFromId === source.id) && c.revisions.some(r =>
    r.number === source.revision && r.title === source.title && r.summary === source.summary && r.body === source.body));
}
export function weaveRequest(draft: WeaveDraft, wholeCards = false) {
  const sources = z.array(snapshotSchema).min(2).max(8).parse(draft.sources);
  const weave = wholeCards ? undefined : validateWeaveInput(weaveInputSchema.parse(draft.weave), sources);
  return { sources, ...(weave ? { weave } : {}) };
}
export function acceptWeave(raw: unknown, request: ReturnType<typeof weaveRequest>): Thought {
  const result = z.object({ card: snapshotSchema.omit({ id: true, revision: true }), contributions: z.array(z.string()).length(request.sources.length), receipt: receiptSchema, weaveMappings: weaveMappingsSchema.optional() }).parse(raw);
  const operation = result.receipt.operation;
  if (operation.kind !== "weave" || stableJson(operation.sources) !== stableJson(request.sources) || stableJson(operation.weave ?? null) !== stableJson(request.weave ?? null)) throw new Error("The result does not match the requested sources and contributions.");
  if (request.weave) validateWeaveMappings(request.weave, result.weaveMappings ?? [], result.card);
  const id = crypto.randomUUID(), contribution = result.contributions.join(" ");
  return { ...result.card, id, revision: 1, contribution, kind: "recombination",
    revisions: [{ ...firstRevision({ ...result.card, contribution }, "generated by Weave"), receipt: result.receipt, ...(request.weave ? { weaveMappings: result.weaveMappings } : {}) }],
    provenance: { feature: "Weave", tag: "feature:weave", sourceTitles: request.sources.map(s => s.title) },
    move: { title: "Explore this direction", question: "Where could this idea lead?", preview: result.card.summary } };
}

export function weaveMarkdown(card: Thought, level: number) {
  const heading = "#".repeat(level);
  return card.revisions.filter(r => r.weaveMappings).map(revision => {
    const op = revision.receipt?.operation ?? revision.experiment?.operation;
    if (!op?.weave) return "";
    return `\n${heading}# Selected contributions · revision ${revision.number}\n\nRequested interaction: ${op.weave.interaction || "Unspecified"}\n` + op.weave.selections.map(selection => {
      const source = op.sources.find(s => s.id === selection.sourceId)!;
      const mapping = revision.weaveMappings!.find(m => m.selectionId === selection.id)!;
      const notes = (card.weaveReviews ?? []).filter(n => n.revision === revision.number && n.selectionId === selection.id);
      return `\n${heading}## ${source.title}\n\nSource: ${source.id}, revision ${source.revision}\n\nCarry forward: ${selection.text}\n${selection.excerpt ? `\nExact ${selection.excerpt.field} excerpt (${selection.excerpt.start}–${selection.excerpt.end}):\n\n${selection.excerpt.text}\n` : ""}\nModel claim (${mapping.status}): ${mapping.explanation}\n${mapping.output ? `\nResult ${mapping.output.field} quotation: ${mapping.output.text}\n` : ""}${notes.map(n => `\nYour interpretation (${n.at}): ${n.text}\n`).join("")}\nSource summary: ${source.summary}\n\nSource body:\n\n${source.body}\n`;
    }).join("\n") + (op.weave.variantOf ? `\nVariant of ${op.weave.variantOf.title}, revision ${op.weave.variantOf.revision}\n` : "");
  }).join("\n");
}
